- name: Add backports repository
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: present
    update_cache: true

- name: Install golang
  package:
    name: "{{ snowflake_packages_deb }}"
    default_release: buster-backports
    state: present

- name: Install required software
  package:
    name: "{{ snowflake_utils }}"
    state: present

- name: Add the user
  ansible.builtin.user:
    name: "{{ snowflake_user }}"
    create_home: true
    state: present

- name: Clone snowflake repo
  ansible.builtin.git:
    repo: 'https://git.torproject.org/pluggable-transports/snowflake.git'
    dest: /home/{{ snowflake_user }}/repo
    update: "{{ snowflake_update }}"
  register: clone_git

- name: go get
  command: go get
  args:
    warn: no
    chdir: /home/{{ snowflake_user }}/repo/proxy
  register: go_get
  when: clone_git is changed

- name: go build
  command: go build
  args:
    warn: no
    chdir: /home/{{ snowflake_user }}/repo/proxy
  register: go_build
  when: clone_git is changed
