# freebsd.yml

- name: Config pkg repo
  tansible.builtin.emplate:
    src: "{{ item }}.j2"
    dest: "/etc/pkg/{{ item }}"
    mode: 0644
  with_items:
    - FreeBSD.conf

- name: Install package snowflake-tor
  community.general.pkgng:
    name: snowflake-tor
    cached: yes
    state: present

- name: Enable snowflake on boot
  community.general.sysrc:
    name: snowflake_enable
    state: present
    value: "YES"

- name: Start service snowflake
  ansible.builtin.service:
    name: snowflake
    state: started
