---
# tasks file for snowflake

- include_tasks: debian.yml
  when:
   - ansible_distribution == 'Debian'
   - ansible_distribution_release == 'buster'

- include_tasks: debian-bullseye.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'bullseye'

- include_tasks: ubuntu.yml
  when:
   - ansible_distribution == 'Ubuntu'
   - ansible_distribution_release == 'focal'

- include_tasks: freebsd.yml
  when:
   - ansible_distribution == 'FreeBSD'
   - ansible_distribution_release == '13.0-RELEASE'

- include_tasks: arch.yml
  when:
   - ansible_distribution == 'Archlinux'

- include_tasks: fedora.yml
  when: ansible_os_family == 'RedHat'
